import type { Metadata } from "next";
import { Sora} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";

const fontFamily = Sora({
  variable: "--font-Sora",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR "suppressHydrationWarning>
      <body
        className={cn(fontFamily.className, " antialiased font-sans ")}
      >
        <SessionProvider>

           {children}
        </SessionProvider>
       
      </body>
    </html>
  );
}
